baseURL = "https://jackbayliss.com/"
languageCode = "en-gb"
title = "Jack Bayliss"
theme = "PaperMod"

[params]
  hideFooter = true
  ShowDate = false
  description = "Jack Bayliss - PHP and Laravel developer from the Black Country, England."
  images = ["/images/emoji.jpg"]

[params.profileMode]
  enabled = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 3
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
